
from CToolKit.amalgamation import  generate_amalgamated_code
from CToolKit.ComandLineExecution import ComandLineExecution
from CToolKit.comand_line_functions import compile_project_by_command
from CToolKit.comand_line_functions import compile_project
from CToolKit.comand_line_functions import test_binary_with_valgrind
from CToolKit.comand_line_functions import execute_test_for_file
from CToolKit.comand_line_functions import execute_test_for_folder


from CToolKit.Errors import *


from CToolKit.readme_converter import include_code_in_markdown

from CToolKit.CodeBuild.Struct import Struct