from CToolKit.amalgamation import  get_amalgamated_code
from CToolKit.comand_line import copile_project_by_command
from CToolKit.comand_line import copile_project
from CToolKit.comand_line import test_binary_with_valgrind

